title: "React Native 〜 JavaScriptによるiOS/Androidアプリ開発の実践"
summary: "技術評論社から出版されていた書籍の内容のうち、現在でも通用する部分を公開。<a href=\"https://zenn.dev/yutama_kotaro/articles/dd30e429693977\">経緯はこちら</a>。"
topics: ["ReactNative"]
published: true
price: 0 # 有料の場合200〜5000
chapters:
  - annotation
  - introduction
  - 01-overview
  - 02-language
  - 06-test
  - 09-redux
  - conclusion
